# fly.toml app configuration file generated for goalgetter-web on 2023-10-02T23:23:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goalgetter-web"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
