# fly.toml app configuration file generated for goalgetter-api on 2023-10-01T19:47:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goalgetter-api"
primary_region = "lhr"

[env]
APP_VERSION = "v0.0.0j"

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
processes = ["app"]
