# fly.toml app configuration file generated for goalgetter-api on 2023-12-29T16:33:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goalgetter-api"
primary_region = "lhr"

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3001
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
