# fly.toml app configuration file generated for goalgetter-api on 2023-09-30T19:13:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goalgetter-api"
primary_region = "lhr"

[build]

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
